# PARTE 1

## Questão 1

In [79]:

import pandas as pd
FILE_PATH = "vendas_quitanda.csv"
df = pd.read_csv(FILE_PATH,sep=";")

## Questão 2

In [80]:
df.shape

(510, 8)

### 518 linhas, 8 colunas.

## Questão 3

In [59]:
df.dtypes

ID               int64
Nome               str
Idade          float64
Cidade             str
Produto            str
Preço              str
Quantidade       int64
Data_Compra        str
dtype: object

### Preço deveria ser float64, contudo devido à inconsistência entre pontos e vírgulas na inserção de valores, o pandas reconheceu como str.

#PARTE 2

## Questão 4

In [60]:
df.isnull().sum()

ID              0
Nome            0
Idade          21
Cidade          0
Produto         0
Preço          37
Quantidade      0
Data_Compra     0
dtype: int64

### Quantidade de valores nulos em cada coluna.

## Questão 5

### Linhas duplicadas:

In [62]:
df[df.duplicated(keep=False)]

,ID,Nome,Idade,Cidade,Produto,Preço,Quantidade,Data_Compra
73,74,Carlos,39.0,SÃO PAULO,Tablet,4035.86,9,27-08-2023
104,105,Mariana,23.0,SALVADOR,Smartphone,2588.98,7,23-02-2025
124,125,João,24.0,MANAUS,Headset,4529.67,5,19-02-2025
361,362,Fernanda,NaN,PORTO ALEGRE,Smartphone,1689.08,7,07-05-2025
374,375,Maria,38.0,FORTALEZA,Mouse,2072.31,7,11-05-2025
377,378,Mariana,62.0,MANAUS,Tablet,3282.26,3,19-05-2025
394,395,Bruno,46.0,CURITIBA,Headset,3321.2,2,24-08-2023
450,451,Carlos,56.0,SALVADOR,Monitor,3383.77,8,04-02-2024
500,362,Fernanda,NaN,PORTO ALEGRE,Smartphone,1689.08,7,07-05-2025
501,74,Carlos,39.0,SÃO PAULO,Tablet,4035.86,9,27-08-2023
502,375,Maria,38.0,FORTALEZA,Mouse,2072.31,7,11-05-2025
504,105,Mariana,23.0,SALVADOR,Smartphone,2588.98,7,23-02-2025
505,395,Bruno,46.0,CURITIBA,Headset,3321.2,2,24-08-2023
506,378,Mariana,62.0,MANAUS,Tablet,3282.26,3,19-05-2025
507,125,João,24.0,MANAUS,Headset,4529.67,5,19-02-2025
509,451,Carlos,56.0,SALVADOR,Monitor,3383.77,8,04-02-2024

### IDs duplicados:

In [81]:
df[df["ID"].duplicated(keep=False)]

,ID,Nome,Idade,Cidade,Produto,Preço,Quantidade,Data_Compra
68,69,João,25.0,BELO HORIZONTE,Headset,3144.09,8,01-02-2024
73,74,Carlos,39.0,SÃO PAULO,Tablet,4035.86,9,27-08-2023
104,105,Mariana,23.0,SALVADOR,Smartphone,2588.98,7,23-02-2025
124,125,João,24.0,MANAUS,Headset,4529.67,5,19-02-2025
155,156,João,47.0,belo horizonte,Smartphone,3444.96,7,28-12-2022
361,362,Fernanda,NaN,PORTO ALEGRE,Smartphone,1689.08,7,07-05-2025
374,375,Maria,38.0,FORTALEZA,Mouse,2072.31,7,11-05-2025
377,378,Mariana,62.0,MANAUS,Tablet,3282.26,3,19-05-2025
394,395,Bruno,46.0,CURITIBA,Headset,3321.2,2,24-08-2023
450,451,Carlos,56.0,SALVADOR,Monitor,3383.77,8,04-02-2024
500,362,Fernanda,NaN,PORTO ALEGRE,Smartphone,1689.08,7,07-05-2025
501,74,Carlos,39.0,SÃO PAULO,Tablet,4035.86,9,27-08-2023
502,375,Maria,38.0,FORTALEZA,Mouse,2072.31,7,11-05-2025
503,156,João,47.0,belo horizonte,Smartphone,"3444,96",7,28-12-2022
504,105,Mariana,23.0,SALVADOR,Smartphone,2588.98,7,23-02-2025
505,395,Bruno,46.0,CURITIBA,Headset,3321.2,2,24-08-2023
506,378,Mariana,62.0,MANAUS,Tablet,3282.26,3,19-05-2025
507,125,João,24.0,MANAUS,Headset,4529.67,5,19-02-2025
508,69,João,25.0,BELO HORIZONTE,Headset,31440.9,8,01-02-2024
509,451,Carlos,56.0,SALVADOR,Monitor,3383.77,8,04-02-2024

### Os IDs acima estão se repetindo.

## Questão 6

In [82]:
df["Cidade"].unique()

<StringArray>
[     'FORTALEZA', 'RIO DE JANEIRO',       'CURITIBA',       'SALVADOR',
   'PORTO ALEGRE',      'SÃO PAULO',       'curitiba',         'MANAUS',
 'BELO HORIZONTE', 'rio de janeiro', 'belo horizonte',   'porto alegre',
       'salvador',         'manaus',      'fortaleza',      'são paulo']
Length: 16, dtype: str

###  Possui tanto apenas maiúsculos como apenas minúsculos, sendo altamente inconsistente.

## Questão 7

In [83]:
df["Preço"].unique()

<StringArray>
['2010,87',       nan, '3619.29', '40415.9',  '716.66', '2388.44', '2363.09',
 '2080.54', '4229,63', '3101.25',
 ...
 '4177,57', '4066.96',  '529.69', '2479.54', '2815.44', '1176.08', '3209.09',
 '3474.99', '3444,96', '31440.9']
Length: 466, dtype: str

### Não, pois é de tipo string, pois possui 2 formatos diferentes de formatação (com . e com ,)

## Questão 8

In [84]:
df["Data_Compra"]

0      30-05-2024
1      12-04-2025
2      10-12-2022
3      31-12-2022
4      14-09-2023
          ...
505    24-08-2023
506    19-05-2025
507    19-02-2025
508    01-02-2024
509    04-02-2024
Name: Data_Compra, Length: 510, dtype: str

### Não está em datas, mas sim em str, que torna impossível agrupamento temporal,amostragem, etc.

# PARTE 3

## Questão 9

In [85]:
df["Idade"].describe()

count    489.000000
mean      44.274029
std       15.320034
min       18.000000
25%       31.000000
50%       44.000000
75%       58.000000
max       70.000000
Name: Idade, dtype: float64

### Fazem sentido contudo poderiam ser int.

## Questão 10

In [86]:
df["Produto"].describe().top

'Smartphone'

### Mais comprado: Smartphone.

## Questão 11

In [90]:
df["Preço"].astype(str).str.replace(",", ".").astype(float).min()

np.float64(509.89)

### Mais baixo: 509,89

In [94]:
df["Preço"].astype(str).str.replace(",", ".").astype(float).max()

np.float64(47611.6)

### Mais alto: 47611,60

# PARTE 4

### Questão 12

## Hipótese 1: Alguma cidade se destaca na compra de um produto em específico?

In [93]:
pd.crosstab(df["Cidade"],df["Produto"],normalize="index")*100

Produto,Headset,Monitor,Mouse,Notebook,Smartphone,Tablet,Teclado
Cidade,,,,,,,
BELO HORIZONTE,27.118644,13.559322,8.474576,15.254237,10.169492,13.559322,11.864407
CURITIBA,15.789474,12.280702,17.543860,21.052632,3.508772,15.789474,14.035088
FORTALEZA,5.357143,7.142857,21.428571,16.071429,17.857143,23.214286,8.928571
MANAUS,15.254237,10.169492,13.559322,13.559322,15.254237,15.254237,16.949153
PORTO ALEGRE,8.955224,8.955224,14.925373,16.417910,22.388060,14.925373,13.432836
RIO DE JANEIRO,5.555556,18.518519,14.814815,14.814815,27.777778,12.962963,5.555556
SALVADOR,14.062500,15.625000,15.625000,10.937500,20.312500,10.937500,12.500000
SÃO PAULO,8.510638,12.765957,17.021277,19.148936,10.638298,14.893617,17.021277
belo horizonte,0.000000,0.000000,28.571429,0.000000,28.571429,14.285714,28.571429
curitiba,0.000000,16.666667,0.000000,16.666667,33.333333,33.333333,0.000000
fortaleza,0.000000,20.000000,0.000000,40.000000,20.000000,0.000000,20.000000
manaus,0.000000,0.000000,25.000000,0.000000,25.000000,25.000000,25.000000
porto alegre,40.000000,20.000000,0.000000,0.000000,10.000000,10.000000,20.000000
rio de janeiro,0.000000,14.285714,28.571429,14.285714,14.285714,0.000000,28.571429
salvador,0.000000,20.000000,60.000000,0.000000,20.000000,0.000000,0.000000
são paulo,0.000000,66.666667,0.000000,0.000000,33.333333,0.000000,0.000000

- Belo Horizonte se destaca na compra de headsets.
- Curitiba, Notebooks.
- Fortaleza, Tablets.
- Manaus, Teclados.
- Porto Alegre, Smartphones.

## Hipótese 2: Existe relação entre a idade do cliente e tipo de produto comprado?

In [92]:
idade_bins= pd.cut(df["Idade"], bins=[0, 25, 40, 60, 100], labels=["18-25", "26-40", "41-60", "60+"])
pd.crosstab(idade_bins, df["Produto"])

Produto  Headset  Monitor  Mouse  Notebook  Smartphone  Tablet  Teclado
Idade
18-25         13        8     12        10          10      11       10
26-40         12       22     21        17          26      23       14
41-60         25       24     29        28          31      23       26
60+           12        9     16        18          12      14       13

### Como visto acima,pessoas de 18-25 anos não compraram muitos produtos em geral, sendo superados por todos os outros grupos etários.

## Hipótese 3: Clientes mais velhos gastam mais dinheiro que clientes mais jovens?

In [91]:
idade_bins=pd.cut(df["Idade"],bins=[0,25,40,60,100],labels=["18-25","26-40","41-60","60+"])
preco_normalizado=df["Preço"].astype(str).str.replace(",", ".").astype(float)
receita=preco_normalizado*df["Quantidade"]
receita.groupby(idade_bins).sum()

Idade
18-25    1451786.73
26-40    2488489.28
41-60    2907787.60
60+      1619020.62
dtype: float64

### Campeão absoluto: 41-60 anos de idade, gastando quase 3 milhões de reais, seguido por 26-40 anos, que gastaram 2,5.