In [3]:
import numpy as np
import pandas as pd

# Dados genéricos com problemas comuns de dados reais
dados = {
    'ID': [101, 102, 103, 104, 105, 106, 107, 107, 108],  # Note o '107' duplicado
    'Nome': [
        'Ana',
        'Bruno',
        'Carla',
        'Diego',
        'Elena',
        'Fábio',
        'Gabi',
        'Gabi',
        'Hugo',
    ],
    'Idade': [25, np.nan, 30, 22, np.nan, 45, 29, 29, 35],  # Valores Nulos
    'Setor': [
        'TI',
        'ti',
        'Vendas',
        ' Vendas ',
        'RH',
        'TI',
        'RH',
        'RH',
        np.nan,
    ],  # Minúsculas, espaços extras e nulo
    'Salario': [
        5000.0,
        4200.0,
        np.nan,
        3100.0,
        6200.0,
        8000.0,
        4900.0,
        4900.0,
        5500.0,
    ],
    'Data_Admissao': [
        '2021-01-15',
        '2020-05-10',
        '2019-11-23',
        None,
        '2022-03-01',
        '2018-07-19',
        '2021-09-30',
        '2021-09-30',
        '2023-02-14',
    ],  # None vira NaT
}

df = pd.DataFrame(dados)
df

    ID   Nome  Idade     Setor  Salario Data_Admissao
0  101    Ana   25.0        TI   5000.0    2021-01-15
1  102  Bruno    NaN        ti   4200.0    2020-05-10
2  103  Carla   30.0    Vendas      NaN    2019-11-23
3  104  Diego   22.0   Vendas    3100.0           NaN
4  105  Elena    NaN        RH   6200.0    2022-03-01
5  106  Fábio   45.0        TI   8000.0    2018-07-19
6  107   Gabi   29.0        RH   4900.0    2021-09-30
7  107   Gabi   29.0        RH   4900.0    2021-09-30
8  108   Hugo   35.0       NaN   5500.0    2023-02-14

In [6]:
df_media=df.dropna()
df_media

    ID   Nome  Idade Setor  Salario Data_Admissao
0  101    Ana   25.0    TI   5000.0    2021-01-15
5  106  Fábio   45.0    TI   8000.0    2018-07-19
6  107   Gabi   29.0    RH   4900.0    2021-09-30
7  107   Gabi   29.0    RH   4900.0    2021-09-30